# Generated by Django 5.0.3 on 2024-03-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cities_city_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.CharField(max_length=255),
        ),
    ]
