# Generated by Django 5.0.3 on 2024-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_weather_humidity_alter_weather_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
